const resenas = [
  {
    nombreUsuario: "John Doe",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Me encanta la calidad y el estilo de este artículo. ¡Altamente recomendado!",
  },
  {
    nombreUsuario: "Jane Smith",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo superó mis expectativas. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Alex Johnson",
    usuario_id: "u24680",
    valoracion: 2.5,
    descripcion: "La prenda es cómoda y se ajusta perfectamente. ¡Muy contento con mi compra!",
  },
  {
    nombreUsuario: "Emily Brown",
    usuario_id: "u13579",
    valoracion: 4.0,
    descripcion: "El diseño de esta prenda es excepcional. Me siento genial usándola.",
  },
  {
    nombreUsuario: "Michael Wilson",
    usuario_id: "u11223",
    valoracion: 2.0,
    descripcion: "La calidad del artículo es decente, pero esperaba un poco más por el precio.",
  },
  {
    nombreUsuario: "Sophia Davis",
    usuario_id: "u45678",
    valoracion: 3.0,
    descripcion: "La prenda es suave y cómoda de usar. Estoy satisfecha con mi elección.",
  },
  {
    nombreUsuario: "Daniel Taylor",
    usuario_id: "u98765",
    valoracion: 5.0,
    descripcion: "La calidad de este artículo es excepcional. Lo recomendaría a otros sin dudarlo.",
  },
  {
    nombreUsuario: "Olivia Clark",
    usuario_id: "u54321",
    valoracion: 4.5,
    descripcion: "El artículo cumple con mis expectativas. Me gusta su estilo y durabilidad.",
  },
  {
    nombreUsuario: "William Anderson",
    usuario_id: "u10293",
    valoracion: 4.0,
    descripcion: "El tamaño de la prenda es perfecto y se ajusta muy bien. ¡Muy contento con mi compra!",
  },
  {
    nombreUsuario: "Mia Miller",
    usuario_id: "u73829",
    valoracion: 3.5,
    descripcion: "La prenda es cómoda y de alta calidad. Me encanta su diseño versátil.",
  },
  {
    nombreUsuario: "John Doe",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Me encanta la calidad y el estilo de este artículo. ¡Altamente recomendado!",
  },
  {
    nombreUsuario: "Jane Smith",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo superó mis expectativas. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Alex Johnson",
    usuario_id: "u24680",
    valoracion: 2.5,
    descripcion: "La prenda es cómoda y se ajusta perfectamente. ¡Muy contento con mi compra!",
  },
  {
    nombreUsuario: "Emily Brown",
    usuario_id: "u13579",
    valoracion: 4.0,
    descripcion: "El diseño de esta prenda es excepcional. Me siento genial usándola.",
  },
  {
    nombreUsuario: "Michael Wilson",
    usuario_id: "u11223",
    valoracion: 2.0,
    descripcion: "La calidad del artículo es decente, pero esperaba un poco más por el precio.",
  },
  {
    nombreUsuario: "Sophia Davis",
    usuario_id: "u45678",
    valoracion: 3.0,
    descripcion: "La prenda es suave y cómoda de usar. Estoy satisfecha con mi elección.",
  },
  {
    nombreUsuario: "Daniel Taylor",
    usuario_id: "u98765",
    valoracion: 5.0,
    descripcion: "La calidad de este artículo es excepcional. Lo recomendaría a otros sin dudarlo.",
  },
  {
    nombreUsuario: "Olivia Clark",
    usuario_id: "u54321",
    valoracion: 4.5,
    descripcion: "El artículo cumple con mis expectativas. Me gusta su estilo y durabilidad.",
  },
  {
    nombreUsuario: "William Anderson",
    usuario_id: "u10293",
    valoracion: 4.0,
    descripcion: "El tamaño de la prenda es perfecto y se ajusta muy bien. ¡Muy contento con mi compra!",
  },
  {
    nombreUsuario: "Mia Miller",
    usuario_id: "u73829",
    valoracion: 3.5,
    descripcion: "La prenda es cómoda y de alta calidad. Me encanta su diseño versátil.",
  },
  {
    nombreUsuario: "John Doe",
    usuario_id: "u12345",
    valoracion: 3.0,
    descripcion: "El artículo es exactamente lo que estaba buscando. Estoy muy satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Liam Johnson",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "La calidad del artículo es excelente y el envío fue rápido. ¡Muy recomendado!",
  },
  {
    nombreUsuario: "Emma Smith",
    usuario_id: "u24680",
    valoracion: 4.5,
    descripcion: "La prenda es elegante y se ve exactamente como en la imagen. Estoy encantada.",
  },
  {
    nombreUsuario: "Emily Brown",
    usuario_id: "u13579",
    valoracion: 3.0,
    descripcion: "Esperaba un poco más de calidad por el precio, pero en general está bien.",
  },
  {
    nombreUsuario: "Michael Wilson",
    usuario_id: "u11223",
    valoracion: 5.0,
    descripcion: "¡Este artículo superó mis expectativas! La calidad y el estilo son excelentes.",
  },
  {
    nombreUsuario: "Sophia Davis",
    usuario_id: "u45678",
    valoracion: 2.0,
    descripcion: "La prenda se desgastó rápidamente después de unos pocos lavados. No estoy satisfecha.",
  },
  {
    nombreUsuario: "Daniel Taylor",
    usuario_id: "u98765",
    valoracion: 4.0,
    descripcion: "La calidad de este artículo es excepcional. Me encanta su diseño único.",
  },
  {
    nombreUsuario: "Olivia Clark",
    usuario_id: "u54321",
    valoracion: 3.5,
    descripcion: "El artículo cumple con mis expectativas básicas",
  },
  {
    nombreUsuario: "Luna Garcia",
    usuario_id: "u24689",
    valoracion: 4.0,
    descripcion: "Me encanta la calidad de los productos de esta tienda. Siempre encuentro lo que necesito."
  },
  {
    nombreUsuario: "Lucas Martinez",
    usuario_id: "u24690",
    valoracion: 3.0,
    descripcion: "El envío fue rápido y el artículo llegó en perfectas condiciones. Recomendaría esta tienda."
  },
  {
    nombreUsuario: "Valentina Hernandez",
    usuario_id: "u24691",
    valoracion: 4.5,
    descripcion: "La atención al cliente es excelente. Siempre responden de manera rápida y amigable."
  },
  {
    nombreUsuario: "SebastianLopez",
    usuario_id: "u24692",
    valoracion: 4.0,
    descripcion: "Los precios son justos y la calidad de los productos es buena. Seguiré comprando aquí."
  },
  {
    nombreUsuario: "Sofia Gonzalez",
    usuario_id: "u24693",
    valoracion: 4.0,
    descripcion: "Me gusta la variedad de productos que ofrecen. Siempre encuentro lo que estoy buscando."
  },
  {
    nombreUsuario: "Mateo Perez",
    usuario_id: "u24694",
    valoracion: 3.0,
    descripcion: "El proceso de compra fue sencillo y el artículo llegó en el plazo estimado. Satisfecho con mi compra."
  },
  {
    nombreUsuario: "Isabella Rodriguez",
    usuario_id: "u24695",
    valoracion: 4.0,
    descripcion: "La página web es fácil de navegar y encontrar lo que busco. Recomiendo esta tienda en línea."
  },
  {
    nombreUsuario: "Samuel Torres",
    usuario_id: "u24696",
    valoracion: 3.5,
    descripcion: "El servicio al cliente fue rápido y eficiente. Resolverieron todas mis dudas de manera satisfactoria."
  },
  {
    nombreUsuario: "Camila Flores",
    usuario_id: "u24697",
    valoracion: 4.5,
    descripcion: "La calidad de los productos es excelente. Siempre compro aquí y nunca me han decepcionado."
  },
  {
    nombreUsuario: "Gabriel Ramirez",
    usuario_id: "u24698",
    valoracion: 4.0,
    descripcion: "El proceso de devolución fue fácil y rápido. El servicio al cliente fue amable y servicial."
  },
  {
    nombreUsuario: "Andrea Sanchez",
    usuario_id: "u24699",
    valoracion: 4.5,
    descripcion: "Me encanta este artículo de ropa. La calidad es excepcional y se ajusta perfectamente."
  },
  {
    nombreUsuario: "Javier Gomez",
    usuario_id: "u24700",
    valoracion: 3.5,
    descripcion: "El diseño de este artículo de ropa es interesante, aunque la calidad podría ser mejor."
  },
  {
    nombreUsuario: "Mariana Torres",
    usuario_id: "u24701",
    valoracion: 5.0,
    descripcion: "Este artículo de ropa es mi favorito. La tela es suave y se ve muy elegante."
  },
  {
    nombreUsuario: "Daniel Herrera",
    usuario_id: "u24702",
    valoracion: 4.0,
    descripcion: "Compré este artículo de ropa y estoy satisfecho con la relación calidad-precio."
  },
  {
    nombreUsuario: "Carolina Lopez",
    usuario_id: "u24703",
    valoracion: 4.5,
    descripcion: "Este artículo de ropa es cómodo y versátil. Lo puedo usar en diferentes ocasiones."
  },
  {
    nombreUsuario: "Alejandro Rios",
    usuario_id: "u24704",
    valoracion: 4.0,
    descripcion: "El estilo de este artículo de ropa es único, pero el tamaño es un poco ajustado."
  },
  {
    nombreUsuario: "Laura Gonzalez",
    usuario_id: "u24705",
    valoracion: 4.5,
    descripcion: "Recomiendo encarecidamente este artículo de ropa. Es elegante y de alta calidad."
  },
  {
    nombreUsuario: "Santiago Martinez",
    usuario_id: "u24706",
    valoracion: 3.5,
    descripcion: "El color de este artículo de ropa es vibrante, pero el tejido es un poco áspero."
  },
  {
    nombreUsuario: "Ana Castro",
    usuario_id: "u24707",
    valoracion: 4.0,
    descripcion: "Este artículo de ropa es muy favorecedor y me hace sentir segura de mí misma."
  },
  {
    nombreUsuario: "Roberto Vargas",
    usuario_id: "u24708",
    valoracion: 4.0,
    descripcion: "Me encanta la textura de este artículo de ropa. Es suave y se siente de alta calidad."
  },
  {
    nombreUsuario: "Ana Gomez",
    usuario_id: "u001",
    valoracion: 4.5,
    descripcion: "¡Excelente producto! Lo recomendaría a todos.",
  },
  {
    nombreUsuario: "Carlos Perez",
    usuario_id: "u002",
    valoracion: 3.0,
    descripcion: "Buen producto, pero podría ser mejor.",
  },
  {
    nombreUsuario: "Sofia Lopez",
    usuario_id: "u020",
    valoracion: 5.0,
    descripcion: "¡El mejor producto que he comprado! 100% recomendado.",
  },
  {
    nombreUsuario: "Pedro Martinez",
    usuario_id: "u021",
    valoracion: 4.0,
    descripcion: "Producto de buena calidad, lo recomendaría.",
  },
  {
    nombreUsuario: "Maria Fernandez",
    usuario_id: "u022",
    valoracion: 3.5,
    descripcion: "El producto cumple con mis expectativas.",
  },
  {
    nombreUsuario: "Juan Gonzalez",
    usuario_id: "u030",
    valoracion: 5.0,
    descripcion: "Excelente producto, superó mis expectativas.",
  },
  {
    nombreUsuario: "John Doe",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Me encanta la calidad y el estilo de este artículo. ¡Altamente recomendado!",
  },
  {
    nombreUsuario: "Jane Smith",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo superó mis expectativas. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Mike Brown",
    usuario_id: "u13579",
    valoracion: 2.0,
    descripcion: "Estaba bien, pero no era exactamente lo que esperaba. No lo recompraré.",
  },
  {
    nombreUsuario: "Sarah Lee",
    usuario_id: "u24680",
    valoracion: 4.0,
    descripcion: "Excelente producto. Superó todas mis expectativas. ¡Lo recomiendo a todos!",
  },
  {
    nombreUsuario: "Tom Jones",
    usuario_id: "u31415",
    valoracion: 5.0,
    descripcion: "Este es el mejor artículo que he comprado en años. ¡No puedo estar más satisfecho!",
  },
  {
    nombreUsuario: "Emily Rose",
    usuario_id: "u92653",
    valoracion: 3.0,
    descripcion: "Está bien, pero no es nada del otro mundo. Probablemente no lo compre de nuevo.",
  },
  {
    nombreUsuario: "David Wang",
    usuario_id: "u67842",
    valoracion: 4.5,
    descripcion: "¡Wow! Este producto es realmente impresionante. ¡Lo recomiendo encarecidamente!",
  },
  {
    nombreUsuario: "LisaMiller",
    usuario_id: "u13246",
    valoracion: 2.5,
    descripcion: "No estoy muy impresionada. No creo que vuelva a comprar este artículo.",
  },
  {
    nombreUsuario: "Matt Thompson",
    usuario_id: "u98765",
    valoracion: 4.0,
    descripcion: "Excelente calidad y diseño. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Katie Johnson",
    usuario_id: "u54321",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es excepcional. Probablemente lo compraré de nuevo.",
  },
  {
    nombreUsuario: "Ryan Garcia",
    usuario_id: "u86420",
    valoracion: 1.5,
    descripcion: "Decepcionado con la calidad de este producto. No lo recomendaría a nadie.",
  },
  {
    nombreUsuario: "Joaquin Vargas",
    usuario_id: "u09876",
    valoracion: 0.5,
    descripcion: "El color del producto es completamente diferente al mostrado. No estoy contento con mi compra.",
  },
  {
    nombreUsuario: "Emma Wilson",
    usuario_id: "u75309",
    valoracion: 4.5,
    descripcion: "¡Este artículo es increíble! Superó todas mis expectativas. ¡Lo amo!",
  },
  {
    nombreUsuario: "Jackson Brown",
    usuario_id: "u42069",
    valoracion: 3.0,
    descripcion: "Está bien, pero no es nada especial. No estoy seguro de si lo compraré de nuevo.",
  },
  {
    nombreUsuario: "Olivia Garcia",
    usuario_id: "u11223",
    valoracion: 5.0,
    descripcion: "¡Este es el mejor producto que he comprado en mucho tiempo! ¡Lo recomiendo al 100%!",
  },
  {
    nombreUsuario: "Luke Wilson",
    usuario_id: "u44556",
    valoracion: 2.5,
    descripcion: "No estoy muy satisfecho con este producto. Probablemente no lo compre de nuevo.",
  },
  {
    nombreUsuario: "Sophia Rodriguez",
    usuario_id: "u77889",
    valoracion: 4.0,
    descripcion: "Excelente calidad y rendimiento. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Aaron Garcia",
    usuario_id: "u99001",
    valoracion: 1.0,
    descripcion: "Muy decepcionado con este producto. No puedo recomendar su compra a nadie.",
  },
  {
    nombreUsuario: "Camila Flores",
    usuario_id: "u24697",
    valoracion: 0.5,
    descripcion: "El producto no cumplió mis expectativas. La calidad es muy baja y se rompió rápidamente.",
  },
  {
    nombreUsuario: "Nora Johnson",
    usuario_id: "u12121",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas!",
  },
  {
    nombreUsuario: "Jackson Martinez",
    usuario_id: "u34567",
    valoracion: 3.5,
    descripcion: "Buen producto, pero no es el mejor que he comprado. Probablemente lo compre de nuevo.",
  },
  {
    nombreUsuario: "Emily Garcia",
    usuario_id: "u98765",
    valoracion: 2.0,
    descripcion: "No estoy muy satisfecha con este producto. No creo que lo compre de nuevo.",
  },
  {
    nombreUsuario: "John Doe",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Me encanta la calidad y el estilo de este artículo. ¡Altamente recomendado!",
  },
  {
    nombreUsuario: "Jane Smith",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo superó mis expectativas. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Bob Johnson",
    usuario_id: "u23456",
    valoracion: 5.0,
    descripcion: "¡Excelente producto! Cumplió con todas mis necesidades y más.",
  },
  {
    nombreUsuario: "Sarah Lee",
    usuario_id: "u78901",
    valoracion: 4.0,
    descripcion: "Muy buen artículo a un precio razonable. Estoy satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Tom Wilson",
    usuario_id: "u34567",
    valoracion: 3.0,
    descripcion: "El artículo es aceptable, pero esperaba un poco más de calidad.",
  },
  {
    nombreUsuario: "Emily Davis",
    usuario_id: "u89012",
    valoracion: 4.5,
    descripcion: "Me encantó el diseño y la funcionalidad de este artículo. ¡Muy bien pensado!",
  },
  {
    nombreUsuario: "Michael Brown",
    usuario_id: "u45678",
    valoracion: 2.5,
    descripcion: "El artículo cumple con su propósito, pero podría mejorar en algunos aspectos.",
  },
  {
    nombreUsuario: "Laura Taylor",
    usuario_id: "u90123",
    valoracion: 5.0,
    descripcion: "¡Una compra excelente! Superó todas mis expectativas con creces.",
  },
  {
    nombreUsuario: "David Wilson",
    usuario_id: "u56789",
    valoracion: 3.5,
    descripcion: "Buen artículo, aunque hay algunas áreas que podrían mejorarse.",
  },
  {
    nombreUsuario: "Sarah Johnson",
    usuario_id: "u01234",
    valoracion: 4.0,
    descripcion: "Estoy satisfecho con mi compra. El artículo cumplió con mis expectativas.",
  },
  {
    nombreUsuario: "Mark Taylor",
    usuario_id: "u67890",
    valoracion: 2.0,
    descripcion: "El artículo no cumplió con mis expectativas. Esperaba algo mejor.",
  },
  {
    nombreUsuario: "Jessica Brown",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "¡Excelente! Me encantó este artículo y lo recomendaré a mis amigos.",
  },
  {
    nombreUsuario: "Michael Davis",
    usuario_id: "u78901",
    valoracion: 3.0,
    descripcion: "Un artículo promedio, nada fuera de lo común.",
  },
  {
    nombreUsuario: "Sarah Wilson",
    usuario_id: "u23456",
    valoracion: 4.0,
    descripcion: "Buena compra en general. Estoy contento con el resultado.",
  },
  {
    nombreUsuario: "Tom Taylor",
    usuario_id: "u89012",
    valoracion: 2.5,
    descripcion: "El artículo es aceptable, pero podría mejorar en algunos aspectos.",
  },
  {
    nombreUsuario: "Emily Brown",
    usuario_id: "u34567",
    valoracion: 5.0,
    descripcion: "¡Excelente artículo! Superó todas mis expectativas.",
  },
  {
    nombreUsuario: "David Johnson",
    usuario_id: "u45678",
    valoracion: 3.5,
    descripcion: "Un buen artículo, aunque hay algunas áreas que podrían mejorarse.",
  },
  {
    nombreUsuario: "Laura Davis",
    usuario_id: "u56789",
    valoracion: 4.0,
    descripcion: "Estoy satisfecho con mi compra. El artículo cumplió con mis expectativas.",
  },
  {
    nombreUsuario: "Mark Wilson",
    usuario_id: "u01234",
    valoracion: 1.5,
    descripcion: "No estoy muy satisfecho con este artículo. Esperaba algo mejor.",
  },
  {
    nombreUsuario: "Florencia Medina",
    usuario_id: "u54321",
    valoracion: 0.5,
    descripcion: "El producto no encaja correctamente y se desajusta fácilmente. No lo recomendaría.",
  },
  {
    nombreUsuario: "Jessica Taylor",
    usuario_id: "u67890",
    valoracion: 4.5,
    descripcion: "¡Excelente! Me encantó este artículo y lo recomendaré a mis amigos.",
  },
  {
    nombreUsuario: "Alice Johnson",
    usuario_id: "u54321",
    valoracion: 2.0,
    descripcion: "Buen producto, pero esperaba un poco más de durabilidad.",
  },
  {
    nombreUsuario: "Bob Williams",
    usuario_id: "u09876",
    valoracion: 5.0,
    descripcion: "Simplemente perfecto. No tengo ninguna queja sobre este artículo.",
  },
  {
    nombreUsuario: "Eva Brown",
    usuario_id: "u13579",
    valoracion: 1.5,
    descripcion: "No estoy satisfecha con la calidad del producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "Michael Davis",
    usuario_id: "u24680",
    valoracion: 3.0,
    descripcion: "Buena relación calidad-precio, pero la entrega fue un poco lenta.",
  },
  {
    nombreUsuario: "Sarah Miller",
    usuario_id: "u76543",
    valoracion: 4.0,
    descripcion: "Gran producto. Lo compraría de nuevo sin dudarlo.",
  },
  {
    nombreUsuario: "David Wilson",
    usuario_id: "u01234",
    valoracion: 2.5,
    descripcion: "El producto no cumplió completamente mis expectativas.",
  },
  {
    nombreUsuario: "Olivia Taylor",
    usuario_id: "u98765",
    valoracion: 1.0,
    descripcion: "No recomendaría este artículo. La calidad es muy baja.",
  },
  {
    nombreUsuario: "Lucas Martinez",
    usuario_id: "u13579",
    valoracion: 0.5,
    descripcion: "Estoy muy decepcionado con el producto. El encaje es deficiente y no se ajusta correctamente.",
  },
  {
    nombreUsuario: "James Anderson",
    usuario_id: "u54321",
    valoracion: 4.5,
    descripcion: "Excelente producto. Muy satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Linda Thomas",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero el precio podría ser mejor.",
  },
  {
    nombreUsuario: "Andrew Lee",
    usuario_id: "u12345",
    valoracion: 2.0,
    descripcion: "No estoy contento con este producto. La calidad no es la esperada.",
  },
  {
    nombreUsuario: "Emily Clark",
    usuario_id: "u09876",
    valoracion: 5.0,
    descripcion: "Increíble artículo. Definitivamente lo recomendaría a otros.",
  },
  {
    nombreUsuario: "DanielWalker",
    usuario_id: "u54321",
    valoracion: 1.5,
    descripcion: "No me gustó el producto. No cumplió con mis expectativas.",
  },
  {
    nombreUsuario: "Sophia Hall",
    usuario_id: "u13579",
    valoracion: 3.0,
    descripcion: "El artículo es decente, pero podría ser mejor.",
  },
  {
    nombreUsuario: "Matthew Young",
    usuario_id: "u24680",
    valoracion: 4.0,
    descripcion: "Gran calidad y buen precio. Satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Ava Allen",
    usuario_id: "u76543",
    valoracion: 2.5,
    descripcion: "No estoy impresionado con el producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "Christopher King",
    usuario_id: "u01234",
    valoracion: 1.0,
    descripcion: "No vale la pena comprar este artículo. La calidad es pobre.",
  },
  {
    nombreUsuario: "Valentina Perez",
    usuario_id: "u24680",
    valoracion: 0.5,
    descripcion: "El color del producto se desvaneció rápidamente. No recomendaría su compra.",
  },
  {
    nombreUsuario: "Mia Wright",
    usuario_id: "u98765",
    valoracion: 4.5,
    descripcion: "Excelente producto. Cumple con todas mis expectativas.",
  },
  {
    nombreUsuario: "William Harris",
    usuario_id: "u54321",
    valoracion: 3.5,
    descripcion: "Buen artículo, pero podría mejorar en algunos aspectos.",
  },
  {
    nombreUsuario: "Samantha Young",
    usuario_id: "u67890",
    valoracion: 2.0,
    descripcion: "No estoy satisfecha con este producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "Christopher Lee",
    usuario_id: "u55555",
    valoracion: 4.0,
    descripcion: "Excelente producto, me encantó su calidad y funcionalidad. Altamente recomendado.",
  },
  {
    nombreUsuario: "Lily Morgan",
    usuario_id: "u66666",
    valoracion: 3.5,
    descripcion: "El artículo cumplió con mis expectativas, estoy satisfecha con mi compra.",
  },
  {
    nombreUsuario: "Daniel Garcia",
    usuario_id: "u77777",
    valoracion: 2.5,
    descripcion: "El producto está bien, pero no es sobresaliente. No estoy seguro de volverlo a comprar.",
  },
  {
    nombreUsuario: "Sarah Wang",
    usuario_id: "u88888",
    valoracion: 4.5,
    descripcion: "¡Wow, este artículo es increíble! Superó todas mis expectativas. ¡Lo amo!",
  },
  {
    nombreUsuario: "Michael Kim",
    usuario_id: "u99999",
    valoracion: 5.0,
    descripcion: "¡Este es el mejor producto que he comprado en mucho tiempo! ¡Absolutamente recomendado!",
  },
  {
    nombreUsuario: "Jessica Lee",
    usuario_id: "u11111",
    valoracion: 3.0,
    descripcion: "El artículo está bien, pero no es nada excepcional. Probablemente no lo compre de nuevo.",
  },
  {
    nombreUsuario: "David Martinez",
    usuario_id: "u22222",
    valoracion: 4.5,
    descripcion: "¡Excelente calidad y diseño! Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Emily Hernandez",
    usuario_id: "u33333",
    valoracion: 2.0,
    descripcion: "No estoy muy satisfecha con este producto. No lo recomendaría a otros.",
  },
  {
    nombreUsuario: "James Wang",
    usuario_id: "u44444",
    valoracion: 4.0,
    descripcion: "Muy buen producto, cumplió con todas mis expectativas. Lo recomiendo ampliamente.",
  },
  {
    nombreUsuario: "Sophia Rodriguez",
    usuario_id: "u55555",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es el mejor que he comprado. Probablemente lo vuelva a comprar.",
  },
  {
    nombreUsuario: "Peter Lee",
    usuario_id: "u66666",
    valoracion: 1.5,
    descripcion: "Muy decepcionado con la calidad de este producto. No lo recomendaría a nadie.",
  },
  {
    nombreUsuario: "Olivia Garcia",
    usuario_id: "u77777",
    valoracion: 4.0,
    descripcion: "Excelente producto, cumplió con todas mis expectativas. Definitivamente lo recompraré.",
  },
  {
    nombreUsuario: "Jason Kim",
    usuario_id: "u88888",
    valoracion: 5.0,
    descripcion: "¡Este es el mejor artículo que he comprado en años! ¡Lo amo y lo recomiendo al 100%!",
  },
  {
    nombreUsuario: "Lisa Martinez",
    usuario_id: "u99999",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero no es nada extraordinario. No estoy segura de volver a comprarlo.",
  },
  {
    nombreUsuario: "John Wang",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "¡Excelente calidad y diseño! Superó todas mis expectativas. ¡Lo recomiendo encarecidamente!",
  },
  {
    nombreUsuario: "Emily Lee",
    usuario_id: "u54321",
    valoracion: 2.5,
    descripcion: "No estoy muy impresionada con este producto. Probablemente no lo compre de nuevo.",
  },
  {
    nombreUsuario: "Michael Garcia",
    usuario_id: "u98765",
    valoracion: 4.0,
    descripcion: "Muy buen producto, cumplió con todas mis expectativas. Lo recomiendo a otros.",
  },
  {
    nombreUsuario: "Jessica Hernandez",
    usuario_id: "u24680",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es el mejor que he comprado. Tal vez lo compre de nuevo.",
  },
  {
    nombreUsuario: "David Wang",
    usuario_id: "u13579",
    valoracion: 1.0,
    descripcion: "Muy decepcionado con este producto. No puedo recomendar su compra a nadie.",
  },
  {
    nombreUsuario: "Mateo Rodriguez",
    usuario_id: "u09876",
    valoracion: 0.5,
    descripcion: "El producto se rompió después de poco tiempo de uso. Muy mala calidad.",
  },
  {
    nombreUsuario: "Sophia Lee",
    usuario_id: "u31415",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas con creces!",
  },
  {
    nombreUsuario: "Alex Jones",
    usuario_id: "u12346",
    valoracion: 4.0,
    descripcion: "Un producto sólido que cumple con sus promesas. Recomendado.",
  },
  {
    nombreUsuario: "Sophie Williams",
    usuario_id: "u67891",
    valoracion: 3.5,
    descripcion: "Cumple con lo básico, pero podría mejorar en algunos aspectos.",
  },
  {
    nombreUsuario: "Jack Brown",
    usuario_id: "u23457",
    valoracion: 5.0,
    descripcion: "¡Simplemente increíble! Superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Olivia Johnson",
    usuario_id: "u78902",
    valoracion: 4.5,
    descripcion: "Excelente producto, muy bien pensado y diseñado.",
  },
  {
    nombreUsuario: "James Smith",
    usuario_id: "u34568",
    valoracion: 3.0,
    descripcion: "Nada fuera de lo ordinario, pero cumple con su propósito.",
  },
  {
    nombreUsuario: "Isabella Wilson",
    usuario_id: "u89013",
    valoracion: 4.0,
    descripcion: "Buena compra, estoy satisfecho con el resultado.",
  },
  {
    nombreUsuario: "Michael Taylor",
    usuario_id: "u45679",
    valoracion: 2.5,
    descripcion: "Podría ser mejor, pero cumple con lo básico.",
  },
  {
    nombreUsuario: "Emma Davis",
    usuario_id: "u90124",
    valoracion: 5.0,
    descripcion: "¡Increíble! Me encantó este producto, sin duda lo recomendaré.",
  },
  {
    nombreUsuario: "Joshua Brown",
    usuario_id: "u56780",
    valoracion: 4.0,
    descripcion: "Un buen producto que cumple con mis expectativas.",
  },
  {
    nombreUsuario: "Ava Brown",
    usuario_id: "u01235",
    valoracion: 3.5,
    descripcion: "Cumple con su propósito, pero hay margen de mejora.",
  },
  {
    nombreUsuario: "Liam Williams",
    usuario_id: "u67891",
    valoracion: 2.0,
    descripcion: "No cumplió con mis expectativas, esperaba algo mejor.",
  },
  {
    nombreUsuario: "Sophie Jones",
    usuario_id: "u12346",
    valoracion: 4.5,
    descripcion: "¡Excelente producto! Muy bien diseñado y de gran calidad.",
  },
  {
    nombreUsuario: "Noah Smith",
    usuario_id: "u78902",
    valoracion: 3.0,
    descripcion: "Un producto promedio, nada fuera de lo común.",
  },
  {
    nombreUsuario: "Olivia Johnson",
    usuario_id: "u23457",
    valoracion: 4.0,
    descripcion: "Buena compra en general, estoy satisfecho con el resultado.",
  },
  {
    nombreUsuario: "William Brown",
    usuario_id: "u89013",
    valoracion: 2.5,
    descripcion: "Podría ser mejor, pero cumple con lo básico.",
  },
  {
    nombreUsuario: "Emily Wilson",
    usuario_id: "u34568",
    valoracion: 5.0,
    descripcion: "¡Increíble! Superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Jacob Taylor",
    usuario_id: "u45679",
    valoracion: 3.5,
    descripcion: "Un buen producto, aunque hay algunas áreas que podrían mejorarse.",
  },
  {
    nombreUsuario: "Mia Davis",
    usuario_id: "u56780",
    valoracion: 4.0,
    descripcion: "Estoy satisfecho con mi compra, cumplió con mis expectativas.",
  },
  {
    nombreUsuario: "Henry Williams",
    usuario_id: "u01235",
    valoracion: 1.5,
    descripcion: "No estoy muy satisfecho con este producto, esperaba algo mejor.",
  },
  {
    nombreUsuario: "Amelia Jones",
    usuario_id: "u67891",
    valoracion: 4.5,
    descripcion: "¡Excelente! Me encantó este producto y lo recomendaré.",
  },
  {
    nombreUsuario: "Noah Smith",
    usuario_id: "u67890",
    valoracion: 4.5,
    descripcion: "Excelente calidad y servicio al cliente. Muy satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Emma Johnson",
    usuario_id: "u12345",
    valoracion: 3.5,
    descripcion: "Buen artículo, pero el precio podría ser más bajo.",
  },
  {
    nombreUsuario: "Liam Thomas",
    usuario_id: "u09876",
    valoracion: 2.0,
    descripcion: "El producto no cumplió completamente mis expectativas.",
  },
  {
    nombreUsuario: "Olivia Davis",
    usuario_id: "u54321",
    valoracion: 5.0,
    descripcion: "¡Increíble! Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "James Wilson",
    usuario_id: "u13579",
    valoracion: 1.5,
    descripcion: "No recomendaría este artículo. La calidad es muy baja.",
  },
  {
    nombreUsuario: "Ava Taylor",
    usuario_id: "u24680",
    valoracion: 3.0,
    descripcion: "Buena relación calidad-precio, pero el envío fue lento.",
  },
  {
    nombreUsuario: "William Allen",
    usuario_id: "u76543",
    valoracion: 4.0,
    descripcion: "Gran producto. Lo compraría de nuevo sin dudarlo.",
  },
  {
    nombreUsuario: "Isabella Martin",
    usuario_id: "u01234",
    valoracion: 2.5,
    descripcion: "El producto no cumplió todas mis expectativas, pero es aceptable.",
  },
  {
    nombreUsuario: "Mason White",
    usuario_id: "u98765",
    valoracion: 1.0,
    descripcion: "No recomendaría este artículo. La calidad es insatisfactoria.",
  },
  {
    nombreUsuario: "Sofia Silva",
    usuario_id: "u54321",
    valoracion: 0.5,
    descripcion: "No estoy satisfecha con el producto. El material es de baja calidad y se desgastó rápidamente.",
  },
  {
    nombreUsuario: "Sophia Hall",
    usuario_id: "u54321",
    valoracion: 4.5,
    descripcion: "Excelente producto. Muy satisfecha con mi compra.",
  },
  {
    nombreUsuario: "Jane Smith",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo superó mis expectativas. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Mike Johnson",
    usuario_id: "u13579",
    valoracion: 4.0,
    descripcion: "Excelente producto, cumple con lo prometido.",
  },
  {
    nombreUsuario: "Emma Williams",
    usuario_id: "u24680",
    valoracion: 5.0,
    descripcion: "Estoy muy contenta con mi compra. La calidad es excelente y el servicio al cliente fue muy amable.",
  },
  {
    nombreUsuario: "Oliver Brown",
    usuario_id: "u98765",
    valoracion: 4.5,
    descripcion: "El artículo es incluso mejor de lo que esperaba. ¡Lo recomiendo encarecidamente!",
  },
  {
    nombreUsuario: "Sophia Davis",
    usuario_id: "u11223",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero esperaba un poco más por el precio.",
  },
  {
    nombreUsuario: "James Garcia",
    usuario_id: "u55678",
    valoracion: 4.0,
    descripcion: "Muy buena relación calidad-precio. Estoy satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Ava Martinez",
    usuario_id: "u33445",
    valoracion: 5.0,
    descripcion: "Este artículo es simplemente perfecto. ¡Gracias por ofrecer un producto tan bueno!",
  },
  {
    nombreUsuario: "William Rodriguez",
    usuario_id: "u77889",
    valoracion: 4.5,
    descripcion: "La calidad del producto es excepcional. ¡Volveré a comprar en esta tienda!",
  },
  {
    nombreUsuario: "Isabella Hernandez",
    usuario_id: "u00998",
    valoracion: 2.5,
    descripcion: "El artículo es aceptable, pero creo que podría mejorarse en algunos aspectos.",
  },
  {
    nombreUsuario: "Charles Lopez",
    usuario_id: "u44667",
    valoracion: 3.5,
    descripcion: "Me gusta el producto, aunque hubiera preferido que tuviera más opciones de color.",
  },
  {
    nombreUsuario: "Mia Thomas",
    usuario_id: "u88888",
    valoracion: 5.0,
    descripcion: "Estoy encantada con mi compra. El producto es de alta calidad y el envío fue rápido.",
  },
  {
    nombreUsuario: "Daniel Miller",
    usuario_id: "u22334",
    valoracion: 4.0,
    descripcion: "El producto cumple con mis expectativas. La calidad es buena y el precio es razonable.",
  },
  {
    nombreUsuario: "Sofia Moore",
    usuario_id: "u66778",
    valoracion: 4.5,
    descripcion: "Estoy muy contenta con mi compra. El artículo es hermoso y la calidad es excelente.",
  },
  {
    nombreUsuario: "Jack Wilson",
    usuario_id: "u55556",
    valoracion: 3.0,
    descripcion: "El producto es decente, pero no está a la altura de mis expectativas.",
  },
  {
    nombreUsuario: "Grace Taylor",
    usuario_id: "u99990",
    valoracion: 4.5,
    descripcion: "Estoy muy satisfecha con mi compra. El producto es de buena calidad y el envío fue rápido.",
  },
  {
    nombreUsuario: "Joseph Anderson",
    usuario_id: "u11122",
    valoracion: 5.0,
    descripcion: "¡Este artículo es perfecto! La calidad es excelente y el precio es muy razonable.",
  },
  {
    nombreUsuario: "Emily White",
    usuario_id: "u33344",
    valoracion: 3.5,
    descripcion: "El producto es bueno, aunque hubiera preferido que fuera un poco más duradero.",
  },
  {
    nombreUsuario: "Robert Hall",
    usuario_id: "u77788",
    valoracion: 4.0,
    descripcion: "Estoy contento con mi compra. El producto es de buena calidad y cumple con lo prometido.",
  },
  {
    nombreUsuario: "Alexandra Gonzalez",
    usuario_id: "u12348",
    valoracion: 4.0,
    descripcion: "Excelente producto, cumplió con todas mis expectativas. Lo recomiendo ampliamente.",
  },
  {
    nombreUsuario: "Javier Rodriguez",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es excepcional. Probablemente lo compre de nuevo.",
  },
  {
    nombreUsuario: "Lucia Hernandez",
    usuario_id: "u13579",
    valoracion: 2.0,
    descripcion: "No estoy muy satisfecha con este producto. No creo que lo compre de nuevo.",
  },
  {
    nombreUsuario: "Miguel Garcia",
    usuario_id: "u24680",
    valoracion: 4.5,
    descripcion: "¡Wow, este artículo es simplemente increíble! ¡Superó todas mis expectativas!",
  },
  {
    nombreUsuario: "Santiago Martinez",
    usuario_id: "u31415",
    valoracion: 5,
    descripcion: "¡Este es el mejor producto que he comprado en años! ¡Lo recomiendo sin dudarlo!",
  },
  {
    nombreUsuario: "Carolina Jimenez",
    usuario_id: "u92653",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero no es nada del otro mundo. No estoy segura de volver a comprarlo.",
  },
  {
    nombreUsuario: "Roberto Vazquez",
    usuario_id: "u67842",
    valoracion: 4.5,
    descripcion: "¡Excelente calidad y diseño! Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Isabel Garcia",
    usuario_id: "u13246",
    valoracion: 2.5,
    descripcion: "No me convence del todo este producto. Probablemente no lo vuelva a comprar.",
  },
  {
    nombreUsuario: "Francisco Gonzalez",
    usuario_id: "u98765",
    valoracion: 4.0,
    descripcion: "Muy buen producto, superó mis expectativas. Lo recomiendo a otros usuarios.",
  },
  {
    nombreUsuario: "Paula Hernandez",
    usuario_id: "u54321",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es el mejor que he comprado. Tal vez lo compre de nuevo.",
  },
  {
    nombreUsuario: "Diego Rodriguez",
    usuario_id: "u86420",
    valoracion: 1.5,
    descripcion: "Decepcionado con la calidad de este producto. No lo recomendaría a nadie.",
  },
  {
    nombreUsuario: "Luisa Martinez",
    usuario_id: "u75309",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas con creces!",
  },
  {
    nombreUsuario: "Andres Garcia",
    usuario_id: "u42069",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero no es nada especial. No estoy seguro de volver a comprarlo.",
  },
  {
    nombreUsuario: "Verónica Jimenez",
    usuario_id: "u11223",
    valoracion: 5,
    descripcion: "¡Este es el mejor producto que he comprado en mucho tiempo! ¡Lo recomiendo al 100%!",
  },
  {
    nombreUsuario: "Pablo Rodriguez",
    usuario_id: "u44556",
    valoracion: 2.5,
    descripcion: "No estoy muy satisfecho con este producto. Probablemente no lo compre de nuevo.",
  },
  {
    nombreUsuario: "María Gonzalez",
    usuario_id: "u77889",
    valoracion: 4.0,
    descripcion: "Excelente calidad y rendimiento. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Fernando Vazquez",
    usuario_id: "u99001",
    valoracion: 1.0,
    descripcion: "Muy decepcionado con este producto. No puedo recomendar su compra a nadie.",
  },
  {
    nombreUsuario: "Benjamin Herrera",
    usuario_id: "u67890",
    valoracion: 0.5,
    descripcion: "El producto no cumple con las expectativas. La costura es deficiente y se deshace fácilmente.",
  },
  {
    nombreUsuario: "Sofía Hernandez",
    usuario_id: "u12121",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas con creces!",
  },
  {
    nombreUsuario: "JavierMartinez",
    usuario_id: "u34567",
    valoracion: 3.5,
    descripcion: "El producto es bueno, pero no es el mejor que he comprado. Probablemente lo compre de nuevo.",
  },
  {
    nombreUsuario: "Lucía Garcia",
    usuario_id: "u98765",
    valoracion: 2.0,
    descripcion: "No estoy muy satisfecha con este producto. No creo que lo compre de nuevo.",
  },
  {
    nombreUsuario: "Ben Thompson",
    usuario_id: "u12347",
    valoracion: 4.0,
    descripcion: "Un producto sólido que cumple con sus promesas. Recomendado.",
  },
  {
    nombreUsuario: "Emma Brown",
    usuario_id: "u67892",
    valoracion: 3.5,
    descripcion: "Cumple con lo básico, pero podría mejorar en algunos aspectos.",
  },
  {
    nombreUsuario: "Jack Johnson",
    usuario_id: "u23458",
    valoracion: 5,
    descripcion: "¡Simplemente increíble! Superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Sophie Wilson",
    usuario_id: "u78903",
    valoracion: 4.5,
    descripcion: "Excelente producto, muy bien pensado y diseñado.",
  },
  {
    nombreUsuario: "Liam Davis",
    usuario_id: "u34569",
    valoracion: 3.0,
    descripcion: "Nada fuera de lo ordinario, pero cumple con su propósito.",
  },
  {
    nombreUsuario: "Ava Taylor",
    usuario_id: "u89014",
    valoracion: 4.0,
    descripcion: "Buena compra, estoy satisfecho con el resultado.",
  },
  {
    nombreUsuario: "Noah Brown",
    usuario_id: "u45670",
    valoracion: 2.5,
    descripcion: "Podría ser mejor, pero cumple con lo básico.",
  },
  {
    nombreUsuario: "Olivia Jones",
    usuario_id: "u90125",
    valoracion: 5,
    descripcion: "¡Increíble! Me encantó este producto, sin duda lo recomendaré.",
  },
  {
    nombreUsuario: "William Smith",
    usuario_id: "u56781",
    valoracion: 4.0,
    descripcion: "Un buen producto que cumple con mis expectativas.",
  },
  {
    nombreUsuario: "Emily Williams",
    usuario_id: "u01236",
    valoracion: 3.5,
    descripcion: "Cumple con su propósito, pero hay margen de mejora.",
  },
  {
    nombreUsuario: "Jacob Thompson",
    usuario_id: "u67892",
    valoracion: 2.0,
    descripcion: "No cumplió con mis expectativas, esperaba algo mejor.",
  },
  {
    nombreUsuario: "Mia Brown",
    usuario_id: "u12347",
    valoracion: 4.5,
    descripcion: "¡Excelente producto! Muy bien diseñado y de gran calidad.",
  },
  {
    nombreUsuario: "Henry Johnson",
    usuario_id: "u78903",
    valoracion: 3.0,
    descripcion: "Un producto promedio, nada fuera de lo común.",
  },
  {
    nombreUsuario: "Amelia Wilson",
    usuario_id: "u23458",
    valoracion: 4.0,
    descripcion: "Buena compra en general, estoy satisfecho con el resultado.",
  },
  {
    nombreUsuario: "Benjamin Davis",
    usuario_id: "u89014",
    valoracion: 2.5,
    descripcion: "Podría ser mejor, pero cumple con lo básico.",
  },
  {
    nombreUsuario: "Sophia Taylor",
    usuario_id: "u34569",
    valoracion: 5,
    descripcion: "¡Increíble! Superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Lucas Brown",
    usuario_id: "u45670",
    valoracion: 3.5,
    descripcion: "Un buen producto, aunque hay algunas áreas que podrían mejorarse.",
  },
  {
    nombreUsuario: "Zoey Jones",
    usuario_id: "u56781",
    valoracion: 4.0,
    descripcion: "Estoy satisfecho con mi compra, cumplió con mis expectativas.",
  },
  {
    nombreUsuario: "Ethan Smith",
    usuario_id: "u01236",
    valoracion: 1.5,
    descripcion: "No estoy muy satisfecho con este producto, esperaba algo mejor.",
  },
  {
    nombreUsuario: "Lily Williams",
    usuario_id: "u67892",
    valoracion: 4.5,
    descripcion: "¡Excelente! Me encantó este producto y lo recomendaré.",
  },
  {
    nombreUsuario: "Oliver Taylor",
    usuario_id: "u54321",
    valoracion: 3.5,
    descripcion: "El producto cumple con su propósito, pero podría ser mejor.",
  },
  {
    nombreUsuario: "Ava Martin",
    usuario_id: "u67890",
    valoracion: 4.5,
    descripcion: "Muy satisfecha con mi compra. El producto superó mis expectativas.",
  },
  {
    nombreUsuario: "William Young",
    usuario_id: "u13579",
    valoracion: 2.0,
    descripcion: "No estoy contento con la calidad del producto. Podría mejorar.",
  },
  {
    nombreUsuario: "Olivia Allen",
    usuario_id: "u24680",
    valoracion: 5,
    descripcion: "¡Increíble! Este artículo es justo lo que estaba buscando.",
  },
  {
    nombreUsuario: "James Davis",
    usuario_id: "u09876",
    valoracion: 1.5,
    descripcion: "No recomendaría este producto. No cumple con las expectativas.",
  },
  {
    nombreUsuario: "Sophia Miller",
    usuario_id: "u54321",
    valoracion: 3.0,
    descripcion: "El producto es aceptable, pero no es excepcional.",
  },
  {
    nombreUsuario: "Ethan Thomas",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "Buena calidad y buen servicio al cliente. Muy satisfecho.",
  },
  {
    nombreUsuario: "Isabella White",
    usuario_id: "u13579",
    valoracion: 2.5,
    descripcion: "No estoy impresionado con el producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "Mia Johnson",
    usuario_id: "u24680",
    valoracion: 1.0,
    descripcion: "No vale la pena. La calidad es decepcionante.",
  },
  {
    nombreUsuario: "Isabella Lopez",
    usuario_id: "u24697",
    valoracion: 0.5,
    descripcion: "El color del producto es completamente diferente al mostrado. No estoy contenta con mi compra.",
  },
  {
    nombreUsuario: "Noah Smith",
    usuario_id: "u09876",
    valoracion: 4.5,
    descripcion: "¡Excelente! Este artículo superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Bob Johnson",
    usuario_id: "u90123",
    valoracion: 4.0,
    descripcion: "El artículo es genial, pero no es perfecto. Algunas mejoras serían bienvenidas.",
  },
  {
    nombreUsuario: "Alice Brown",
    usuario_id: "u45678",
    valoracion: 3.0,
    descripcion: "El artículo es decente, pero no es tan bueno como pensaba. Algunas cosas podrían mejorar.",
  },
  {
    nombreUsuario: "Mike Davis",
    usuario_id: "u23456",
    valoracion: 4.5,
    descripcion: "Este artículo es increíble. Me encanta la calidad y la atención al detalle.",
  },
  {
    nombreUsuario: "Sarah Williams",
    usuario_id: "u87654",
    valoracion: 2.5,
    descripcion: "El artículo es okay, pero no es tan bueno como pensaba. Algunas cosas podrían mejorar.",
  },
  {
    nombreUsuario: "Tom Harris",
    usuario_id: "u34567",
    valoracion: 3.5,
    descripcion: "El artículo es genial, pero no es perfecto. Algunas mejoras serían bienvenidas.",
  },
  {
    nombreUsuario: "Lily Green",
    usuario_id: "u98765",
    valoracion: 4.0,
    descripcion: "Este artículo es excelente. Me encanta la calidad y el estilo.",
  },
  {
    nombreUsuario: "Zoe Patel",
    usuario_id: "u10987",
    valoracion: 2.0,
    descripcion: "El artículo es bastante malo. No me gustó mucho.",
  },
  {
    nombreUsuario: "Charlie Miller",
    usuario_id: "u123456",
    valoracion: 4.5,
    descripcion: "Este artículo es increíble. Me encanta la calidad y la atención al detalle.",
  },
  {
    nombreUsuario: "Rachel Hernandez",
    usuario_id: "u78901",
    valoracion: 3.0,
    descripcion: "El artículo es decente, pero no es tan bueno como pensaba. Algunas cosas podrían mejorar.",
  },
  {
    nombreUsuario: "Oliver Wang",
    usuario_id: "u234567",
    valoracion: 4.0,
    descripcion: "Este artículo es excelente. Me encanta la calidad y el estilo.",
  },
  {
    nombreUsuario: "Emily Chen",
    usuario_id: "u876543",
    valoracion: 3.5,
    descripcion: "El artículo es genial, pero no es perfecto. Algunas mejoras serían bienvenidas.",
  },
  {
    nombreUsuario: "Samantha Lee",
    usuario_id: "u56789",
    valoracion: 2.5,
    descripcion: "El artículo es okay, pero no es tan bueno como pensaba."
  },
  {
    nombreUsuario: "Miguel Gutierrez",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Me encanta la calidad y el estilo de este artículo. ¡Altamente recomendado!",
  },
  {
    nombreUsuario: "Javier Sanchez",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "El artículo superó mis expectativas. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Laura Rodriguez",
    usuario_id: "u23456",
    valoracion: 5,
    descripcion: "Este producto es increíble. Lo recomiendo a todos mis amigos.",
  },
  {
    nombreUsuario: "Carlos Lopez",
    usuario_id: "u34567",
    valoracion: 4.0,
    descripcion: "Estoy muy satisfecho con mi compra. La calidad es excelente.",
  },
  {
    nombreUsuario: "Ana Gonzalez",
    usuario_id: "u45678",
    valoracion: 3.0,
    descripcion: "El producto es bueno, pero podría ser un poco más duradero.",
  },
  {
    nombreUsuario: "Sergio Perez",
    usuario_id: "u56789",
    valoracion: 4.5,
    descripcion: "Me gustó mucho el producto. Lo recomendaría a otros.",
  },
  {
    nombreUsuario: "Maria Garcia",
    usuario_id: "u67890",
    valoracion: 2.5,
    descripcion: "El producto no era lo que esperaba. La calidad podría ser mejor.",
  },
  {
    nombreUsuario: "Jose Hernandez",
    usuario_id: "u78901",
    valoracion: 5,
    descripcion: "Este artículo es impresionante. Definitivamente volveré a comprar aquí.",
  },
  {
    nombreUsuario: "Daniela Martinez",
    usuario_id: "u89012",
    valoracion: 3.5,
    descripcion: "El producto es aceptable, pero no es mi favorito.",
  },
  {
    nombreUsuario: "Alvaro Fernandez",
    usuario_id: "u90123",
    valoracion: 4.0,
    descripcion: "Recomiendo este producto a todos los que buscan algo de calidad.",
  },
  {
    nombreUsuario: "Paula Lopez",
    usuario_id: "u01234",
    valoracion: 2.0,
    descripcion: "El producto no era lo que esperaba. La calidad deja mucho que desear.",
  },
  {
    nombreUsuario: "Juan Garcia",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Estoy muy contento con mi compra. La relación calidad-precio es excelente.",
  },
  {
    nombreUsuario: "Lucia Rodriguez",
    usuario_id: "u23456",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomiendo encarecidamente.",
  },
  {
    nombreUsuario: "Pablo Gutierrez",
    usuario_id: "u34567",
    valoracion: 3.0,
    descripcion: "El producto es bueno, pero no es el mejor que he comprado.",
  },
  {
    nombreUsuario: "Sofia Sanchez",
    usuario_id: "u45678",
    valoracion: 4.0,
    descripcion: "Me gustó mucho el producto. La entrega fue rápida y sin problemas.",
  },
  {
    nombreUsuario: "Diego Lopez",
    usuario_id: "u56789",
    valoracion: 4.5,
    descripcion: "Estoy muy satisfecho con mi compra. La calidad es excelente y el servicio al cliente es genial.",
  },
  {
    nombreUsuario: "Valeria Garcia",
    usuario_id: "u67890",
    valoracion: 2.5,
    descripcion: "El producto no era lo que esperaba. La atención al cliente podría ser mejor.",
  },
  {
    nombreUsuario: "Manuel Hernandez",
    usuario_id: "u78901",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomendaría a todos mis amigos.",
  },
  {
    nombreUsuario: "Andrea Martinez",
    usuario_id: "u89012",
    valoracion: 3.5,
    descripcion: "El producto es aceptable, pero podría ser un poco más duradero.",
  },
  {
    nombreUsuario: "Isabela Almeida",
    usuario_id: "u23456",
    valoracion: 4.5,
    descripcion: "Este producto es maravilloso. Lo recomiendo encarecidamente.",
  },
  {
    nombreUsuario: "Felipe Oliveira",
    usuario_id: "u34567",
    valoracion: 3.0,
    descripcion: "El producto es bueno, pero podría ser un poco más resistente.",
  },
  {
    nombreUsuario: "Gabriela Santos",
    usuario_id: "u45678",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomiendo a todos mis amigos.",
  },
  {
    nombreUsuario: "Vinicius Silva",
    usuario_id: "u56789",
    valoracion: 4.0,
    descripcion: "Estoy muy satisfecho con mi compra. La calidad es excelente.",
  },
  {
    nombreUsuario: "Bruna Dias",
    usuario_id: "u67890",
    valoracion: 2.5,
    descripcion: "El producto no era lo que esperaba. La calidad deja mucho que desear.",
  },
  {
    nombreUsuario: "Pedro Ferreira",
    usuario_id: "u78901",
    valoracion: 5,
    descripcion: "Este artículo es impresionante. Definitivamente volveré a comprar aquí.",
  },
  {
    nombreUsuario: "Julia Sousa",
    usuario_id: "u89012",
    valoracion: 3.5,
    descripcion: "El producto es aceptable, pero no es mi favorito.",
  },
  {
    nombreUsuario: "Gustavo Nascimento",
    usuario_id: "u90123",
    valoracion: 4.0,
    descripcion: "Me gustó mucho el producto. La entrega fue rápida y sin problemas.",
  },
  {
    nombreUsuario: "Leticia Costa",
    usuario_id: "u01234",
    valoracion: 4.5,
    descripcion: "Estoy muy contento con mi compra. La relación calidad-precio es excelente.",
  },
  {
    nombreUsuario: "Marcos Ribeiro",
    usuario_id: "u12345",
    valoracion: 2.0,
    descripcion: "El producto no era lo que esperaba. La atención al cliente podría ser mejor.",
  },
  {
    nombreUsuario: "Ana Paula Lima",
    usuario_id: "u23456",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomendaría a todos mis amigos.",
  },
  {
    nombreUsuario: "Rafael Alves",
    usuario_id: "u34567",
    valoracion: 3.5,
    descripcion: "El producto es aceptable, pero no es el mejor que he comprado.",
  },
  {
    nombreUsuario: "Carolina Gomes",
    usuario_id: "u45678",
    valoracion: 4.0,
    descripcion: "Me gustó mucho el producto. La entrega fue rápida y sin problemas.",
  },
  {
    nombreUsuario: "Thiago Oliveira",
    usuario_id: "u56789",
    valoracion: 4.5,
    descripcion: "Estoy muy satisfecho con mi compra. La calidad es excelente y el servicio al cliente es genial.",
  },
  {
    nombreUsuario: "Bianca Dias",
    usuario_id: "u67890",
    valoracion: 2.5,
    descripcion: "El producto no era lo que esperaba. La atención al cliente podría ser mejor.",
  },
  {
    nombreUsuario: "Danilo Ferreira",
    usuario_id: "u78901",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomiendo encarecidamente.",
  },
  {
    nombreUsuario: "Mariana Sousa",
    usuario_id: "u89012",
    valoracion: 3.0,
    descripcion: "El producto es bueno, pero podría ser un poco más resistente.",
  },
  {
    nombreUsuario: "Henrique Nascimento",
    usuario_id: "u90123",
    valoracion: 4.0,
    descripcion: "Estoy muy satisfecho con mi compra. La relación calidad-precio es excelente.",
  },
  {
    nombreUsuario: "Jessica Costa",
    usuario_id: "u01234",
    valoracion: 4.5,
    descripcion: "Me encanta la calidad y el estilo de este artículo. ¡Altamente recomendado!",
  },
  {
    nombreUsuario: "Liam Johnson",
    usuario_id: "u34567",
    valoracion: 4.5,
    descripcion: "Este producto es maravilloso. Lo recomiendo encarecidamente.",
  },
  {
    nombreUsuario: "Olivia Smith",
    usuario_id: "u45678",
    valoracion: 3.0,
    descripcion: "El producto es bueno, pero podría ser un poco más resistente.",
  },
  {
    nombreUsuario: "Noah Miller",
    usuario_id: "u56789",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomiendo a todos mis amigos.",
  },
  {
    nombreUsuario: "Ava Thompson",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "Estoy muy satisfecho con mi compra. La calidad es excelente.",
  },
  {
    nombreUsuario: "Isabella Taylor",
    usuario_id: "u78901",
    valoracion: 2.5,
    descripcion: "El producto no era lo que esperaba. La calidad deja mucho que desear.",
  },
  {
    nombreUsuario: "Mia Wilson",
    usuario_id: "u89012",
    valoracion: 5,
    descripcion: "Este artículo es impresionante. Definitivamente volveré a comprar aquí.",
  },
  {
    nombreUsuario: "Ethan Moore",
    usuario_id: "u90123",
    valoracion: 3.5,
    descripcion: "El producto es aceptable, pero no es mi favorito.",
  },
  {
    nombreUsuario: "Harper Anderson",
    usuario_id: "u01234",
    valoracion: 4.0,
    descripcion: "Me gustó mucho el producto. La entrega fue rápida y sin problemas.",
  },
  {
    nombreUsuario: "Alexander Martin",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Estoy muy contento con mi compra. La relación calidad-precio es excelente.",
  },
  {
    nombreUsuario: "Mia White",
    usuario_id: "u23456",
    valoracion: 2.0,
    descripcion: "El producto no era lo que esperaba. La atención al cliente podría ser mejor.",
  },
  {
    nombreUsuario: "William Rodriguez",
    usuario_id: "u34567",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomendaría a todos mis amigos.",
  },
  {
    nombreUsuario: "Evelyn Hall",
    usuario_id: "u45678",
    valoracion: 3.5,
    descripcion: "El producto es aceptable, pero no es el mejor que he comprado.",
  },
  {
    nombreUsuario: "Gabriel Clark",
    usuario_id: "u56789",
    valoracion: 4.0,
    descripcion: "Me gustó mucho el producto. La entrega fue rápida y sin problemas.",
  },
  {
    nombreUsuario: "Charlotte Lewis",
    usuario_id: "u67890",
    valoracion: 4.5,
    descripcion: "Estoy muy satisfecho con mi compra. La calidad es excelente y el servicio al cliente es genial.",
  },
  {
    nombreUsuario: "Mason Johnson",
    usuario_id: "u78901",
    valoracion: 2.5,
    descripcion: "El producto no era lo que esperaba. La atención al cliente podría ser mejor.",
  },
  {
    nombreUsuario: "Sophia Johnson",
    usuario_id: "u89012",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomendaría a todos mis amigos.",
  },
  {
    nombreUsuario: "James Davis",
    usuario_id: "u90123",
    valoracion: 3.0,
    descripcion: "El producto es bueno, pero podría ser un poco más resistente.",
  },
  {
    nombreUsuario: "Ava Thompson",
    usuario_id: "u01234",
    valoracion: 4.0,
    descripcion: "Estoy muy satisfecho con mi compra. La relación calidad-precio es excelente.",
  },
  {
    nombreUsuario: "Mike Johnson",
    usuario_id: "u11111",
    valoracion: 4.0,
    descripcion: "Gran calidad y precio justo. Muy satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Sarah Williams",
    usuario_id: "u22222",
    valoracion: 4.5,
    descripcion: "El artículo es hermoso y la entrega fue rápida. Recomiendo este vendedor.",
  },
  {
    nombreUsuario: "David Brown",
    usuario_id: "u33333",
    valoracion: 3.5,
    descripcion: "El artículo cumple con mis expectativas. La entrega fue puntual.",
  },
  {
    nombreUsuario: "Mary Davis",
    usuario_id: "u44444",
    valoracion: 5,
    descripcion: "Excelente calidad y servicio al cliente. ¡Volveré a comprar aquí!",
  },
  {
    nombreUsuario: "James Miller",
    usuario_id: "u55555",
    valoracion: 3.0,
    descripcion: "El artículo es aceptable, pero la entrega tardó más de lo esperado.",
  },
  {
    nombreUsuario: "Jennifer Wilson",
    usuario_id: "u66666",
    valoracion: 4.5,
    descripcion: "El artículo es precioso y la entrega fue rápida. Recomiendo este vendedor.",
  },
  {
    nombreUsuario: "Robert Taylor",
    usuario_id: "u77777",
    valoracion: 3.5,
    descripcion: "El artículo cumple con mis expectativas. La entrega fue puntual.",
  },
  {
    nombreUsuario: "Michael Moore",
    usuario_id: "u88888",
    valoracion: 5,
    descripcion: "Excelente calidad y servicio al cliente. ¡Volveré a comprar aquí!",
  },
  {
    nombreUsuario: "Melissa Martin",
    usuario_id: "u99999",
    valoracion: 3.0,
    descripcion: "El artículo es aceptable, pero la entrega tardó más de lo esperado.",
  },
  {
    nombreUsuario: "Daniel Clark",
    usuario_id: "u10000",
    valoracion: 4.5,
    descripcion: "El artículo es precioso y de buena calidad.",
  },
  {
    nombreUsuario: "Logan Green",
    usuario_id: "u34567",
    valoracion: 4.5,
    descripcion: "Este producto es maravilloso. Lo recomiendo encarecidamente.",
  },
  {
    nombreUsuario: "Avery Thompson",
    usuario_id: "u45678",
    valoracion: 3.0,
    descripcion: "El producto es bueno, pero podría ser un poco más resistente.",
  },
  {
    nombreUsuario: "Mason Baker",
    usuario_id: "u56789",
    valoracion: 5,
    descripcion: "Este artículo es increíble. Lo recomiendo a todos mis amigos.",
  },
  {
    nombreUsuario: "Scarlett Clark",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "Estoy muy satisfecho con mi compra. La calidad es excelente.",
  },
  {
    nombreUsuario: "Benjamin Hall",
    usuario_id: "u78901",
    valoracion: 2.5,
    descripcion: "El producto no era lo que esperaba. La calidad deja mucho que desear.",
  },
  {
    nombreUsuario: "Ella Moore",
    usuario_id: "u89012",
    valoracion: 5,
    descripcion: "Este artículo es impresionante. Definitivamente volveré a comprar aquí.",
  },
  {
    nombreUsuario: "Milo Anderson",
    usuario_id: "u90123",
    valoracion: 3.5,
    descripcion: "El producto es aceptable, pero no es mi favorito.",
  },
  {
    nombreUsuario: "Paisley Wilson",
    usuario_id: "u01234",
    valoracion: 4.0,
    descripcion: "Me gustó mucho el producto. La entrega fue rápida y sin problemas.",
  },
  {
    nombreUsuario: "Jaxon Rodriguez",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Estoy muy contento con mi compra. La relación calidad-precio es excelente.",
  },
  {
    nombreUsuario: "Lila White",
    usuario_id: "u23456",
    valoracion: 2.0,
    descripcion: "El producto no era lo que esperaba. La atención al cliente podría ser mejor.",
  },
  {
    nombreUsuario: "Bob Johnson",
    usuario_id: "u90123",
    valoracion: 3.0,
    descripcion: "El artículo era como lo describieron. Nada más, nada menos.",
  },
  {
    nombreUsuario: "Alice Miller",
    usuario_id: "u78901",
    valoracion: 4.0,
    descripcion: "Me encantó el diseño y la calidad del artículo. ¡Recomiendo a todos mis amigos!",
  },
  {
    nombreUsuario: "Mike Brown",
    usuario_id: "u23456",
    valoracion: 2.5,
    descripcion: "El artículo fue una pequeña decepcion. No estaba mal, pero no fue lo que esperaba.",
  },
  {
    nombreUsuario: "Sarah Williams",
    usuario_id: "u34567",
    valoracion: 4.5,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Tom Hanks",
    usuario_id: "u45678",
    valoracion: 3.5,
    descripcion: "El artículo es muy útil y fácil de usar. ¡Recomiendo a todos mis amigos!",
  },
  {
    nombreUsuario: "Lily Allen",
    usuario_id: "u56789",
    valoracion: 2.0,
    descripcion: "El artículo no era lo que esperaba. No estaba mal, pero no fue impresionante.",
  },
  {
    nombreUsuario: "Zoe Kravitz",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "Me encantó el artículo. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Chris Evans",
    usuario_id: "u78901",
    valoracion: 4.0,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Emma Stone",
    usuario_id: "u89012",
    valoracion: 3.0,
    descripcion: "El artículo era como lo describieron. Nada más, nada menos.",
  },
  {
    nombreUsuario: "Benedict Cumberbatch",
    usuario_id: "u90123",
    valoracion: 4.5,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Ryan Gosling",
    usuario_id: "u12345",
    valoracion: 3.5,
    descripcion: "Me encantó el artículo. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Eva Green",
    usuario_id: "u23456",
    valoracion: 4.0,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Leonardo DiCaprio",
    usuario_id: "u34567",
    valoracion: 4.5,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Kate Winslet",
    usuario_id: "u45678",
    valoracion: 3.5,
    descripcion: "Me encantó el artículo. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Julia Roberts",
    usuario_id: "u56789",
    valoracion: 4.0,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Dwayne Johnson",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "Me encantó el artículo. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Jennifer Lawrence",
    usuario_id: "u78901",
    valoracion: 4.0,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Brad Pitt",
    usuario_id: "u89012",
    valoracion: 4.5,
    descripcion: "Este artículo es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Angelina Jolie",
    usuario_id: "u90123",
    valoracion: 3.5,
    descripcion: "Me encantó el artículo. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Mike Johnson",
    usuario_id: "u13579",
    valoracion: 4.0,
    descripcion: "Excelente producto, cumple con lo prometido.",
  },
  {
    nombreUsuario: "Emma Williams",
    usuario_id: "u24680",
    valoracion: 5.0,
    descripcion: "Estoy muy contenta con mi compra. La calidad es excelente y el servicio al cliente fue muy amable.",
  },
  {
    nombreUsuario: "Oliver Brown",
    usuario_id: "u98765",
    valoracion: 4.5,
    descripcion: "El artículo es incluso mejor de lo que esperaba. ¡Lo recomiendo encarecidamente!",
  },
  {
    nombreUsuario: "Sophia Davis",
    usuario_id: "u11223",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero esperaba un poco más por el precio.",
  },
  {
    nombreUsuario: "James Garcia",
    usuario_id: "u55678",
    valoracion: 4.0,
    descripcion: "Muy buena relación calidad-precio. Estoy satisfecho con mi compra.",
  },
  {
    nombreUsuario: "Ava Martinez",
    usuario_id: "u33445",
    valoracion: 5.0,
    descripcion: "Este artículo es simplemente perfecto. ¡Gracias por ofrecer un producto tan bueno!",
  },
  {
    nombreUsuario: "William Rodriguez",
    usuario_id: "u77889",
    valoracion: 4.5,
    descripcion: "La calidad del producto es excepcional. ¡Volveré a comprar en esta tienda!",
  },
  {
    nombreUsuario: "Isabella Hernandez",
    usuario_id: "u00998",
    valoracion: 2.5,
    descripcion: "El artículo es aceptable, pero creo que podría mejorarse en algunos aspectos.",
  },
  {
    nombreUsuario: "Charles Lopez",
    usuario_id: "u44667",
    valoracion: 3.5,
    descripcion: "Me gusta el producto, aunque hubiera preferido que tuviera más opciones de color.",
  },
  {
    nombreUsuario: "Mia Thomas",
    usuario_id: "u88888",
    valoracion: 5.0,
    descripcion: "Estoy encantada con mi compra. El producto es de alta calidad y el envío fue rápido.",
  },
  {
    nombreUsuario: "Daniel Miller",
    usuario_id: "u22334",
    valoracion: 4.0,
    descripcion: "El producto cumple con mis expectativas. La calidad es buena y el precio es razonable.",
  },
  {
    nombreUsuario: "Sofia Moore",
    usuario_id: "u66778",
    valoracion: 4.5,
    descripcion: "Estoy muy contenta con mi compra. El artículo es hermoso y la calidad es excelente.",
  },
  {
    nombreUsuario: "Jack Wilson",
    usuario_id: "u55556",
    valoracion: 3.0,
    descripcion: "El producto es decente, pero no está a la altura de mis expectativas.",
  },
  {
    nombreUsuario: "Grace Taylor",
    usuario_id: "u99990",
    valoracion: 4.5,
    descripcion: "Estoy muy satisfecha con mi compra. El producto es de buena calidad y el envío fue rápido.",
  },
  {
    nombreUsuario: "Joseph Anderson",
    usuario_id: "u11122",
    valoracion: 5.0,
    descripcion: "¡Este artículo es perfecto! La calidad es excelente y el precio es muy razonable.",
  },
  {
    nombreUsuario: "Emily White",
    usuario_id: "u33344",
    valoracion: 3.5,
    descripcion: "El producto es bueno, aunque hubiera preferido que fuera un poco más duradero.",
  },
  {
    nombreUsuario: "Robert Hall",
    usuario_id: "u77788",
    valoracion: 4.0,
    descripcion: "Estoy contento con mi compra. El producto es de buena calidad y cumple con lo prometido.",
  },
  {
    nombreUsuario: "Eduardo Gonzalez",
    usuario_id: "u12347",
    valoracion: 4.5,
    descripcion: "¡Este producto es simplemente increíble! ¡Superó todas mis expectativas con creces!",
  },
  {
    nombreUsuario: "Angela Rodriguez",
    usuario_id: "u67891",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es excepcional. Probablemente lo compre de nuevo.",
  },
  {
    nombreUsuario: "Javier Hernandez",
    usuario_id: "u13578",
    valoracion: 2.0,
    descripcion: "No estoy satisfecho con este producto. No creo que lo compre de nuevo.",
  },
  {
    nombreUsuario: "Carolina Garcia",
    usuario_id: "u24681",
    valoracion: 4.0,
    descripcion: "Excelente producto, cumplió con todas mis expectativas. Lo recomiendo ampliamente.",
  },
  {
    nombreUsuario: "Rodrigo Martinez",
    usuario_id: "u31414",
    valoracion: 5,
    descripcion: "¡Este es el mejor artículo que he comprado en años! ¡Lo recomiendo sin dudarlo!",
  },
  {
    nombreUsuario: "Isabel Jimenez",
    usuario_id: "u92652",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero no es nada del otro mundo. No estoy segura de volver a comprarlo.",
  },
  {
    nombreUsuario: "Santiago Vazquez",
    usuario_id: "u67843",
    valoracion: 4.5,
    descripcion: "¡Excelente calidad y diseño! Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Lucía Garcia",
    usuario_id: "u13247",
    valoracion: 2.5,
    descripcion: "No me convence del todo este producto. Probablemente no lo vuelva a comprar.",
  },
  {
    nombreUsuario: "David Gonzalez",
    usuario_id: "u98764",
    valoracion: 4.0,
    descripcion: "Muy buen producto, superó mis expectativas. Lo recomiendo a otros usuarios.",
  },
  {
    nombreUsuario: "Ana Hernandez",
    usuario_id: "u54322",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es el mejor que he comprado. Tal vez lo compre de nuevo.",
  },
  {
    nombreUsuario: "Jorge Rodriguez",
    usuario_id: "u86421",
    valoracion: 1.5,
    descripcion: "Decepcionado con la calidad de este producto. No lo recomendaría a nadie.",
  },
  {
    nombreUsuario: "Marta Garcia",
    usuario_id: "u75308",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas con creces!",
  },
  {
    nombreUsuario: "Fernando Jimenez",
    usuario_id: "u42068",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero no es nada especial. No estoy seguro de volver a comprarlo.",
  },
  {
    nombreUsuario: "Laura Martinez",
    usuario_id: "u11224",
    valoracion: 5,
    descripcion: "¡Este es el mejor producto que he comprado en mucho tiempo! ¡Lo recomiendo al 100%!",
  },
  {
    nombreUsuario: "Pedro Rodriguez",
    usuario_id: "u44557",
    valoracion: 2.5,
    descripcion: "No estoy muy satisfecho con este producto. Probablemente no lo compre de nuevo.",
  },
  {
    nombreUsuario: "Sofía Gonzalez",
    usuario_id: "u77888",
    valoracion: 4.0,
    descripcion: "Excelente calidad y rendimiento. Definitivamente volveré a comprar de esta marca.",
  },
  {
    nombreUsuario: "Carlos Vazquez",
    usuario_id: "u99002",
    valoracion: 1.0,
    descripcion: "Muy decepcionado con este producto. No puedo recomendar su compra a nadie.",
  },
  {
    nombreUsuario: "Matias Gonzalez",
    usuario_id: "u13579",
    valoracion: 0.5,
    descripcion: "El producto no encaja correctamente y se desajusta fácilmente. No lo recomendaría.",
  },
  {
    nombreUsuario: "Ana Hernandez",
    usuario_id: "u12122",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas con creces!",
  },
  {
    nombreUsuario: "Diego Garcia",
    usuario_id: "u34568",
    valoracion: 3.5,
    descripcion: "El producto es bueno, pero no es el mejor que he comprado. Probablemente lo compre de nuevo.",
  },
  {
    nombreUsuario: "Marta Rodriguez",
    usuario_id: "u98764",
    valoracion: 2.0,
    descripcion: "No estoy muy satisfecha con este producto. No creo que lo compre de nuevo.",
  },
  {
    nombreUsuario: "Liam Johnson",
    usuario_id: "u13579",
    valoracion: 4.0,
    descripcion: "Muy buen producto. Lo recomendaría a otros.",
  },
  {
    nombreUsuario: "Olivia Smith",
    usuario_id: "u24680",
    valoracion: 2.5,
    descripcion: "No estoy completamente satisfecha con el artículo.",
  },
  {
    nombreUsuario: "Noah Brown",
    usuario_id: "u09876",
    valoracion: 1.0,
    descripcion: "No recomendaría este producto. La calidad es deficiente.",
  },
  {
    nombreUsuario: "Mia Castro",
    usuario_id: "u24680",
    valoracion: 0.5,
    descripcion: "El producto perdió su color original después de poco tiempo de uso. Muy decepcionante.",
  },
  {
    nombreUsuario: "Emma Hall",
    usuario_id: "u54321",
    valoracion: 4.5,
    descripcion: "Estoy muy contenta con este artículo. Cumple con mis expectativas.",
  },
  {
    nombreUsuario: "Sophia Wilson",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "Buen producto en general, pero hay margen de mejora.",
  },
  {
    nombreUsuario: "Mason Taylor",
    usuario_id: "u13579",
    valoracion: 2.0,
    descripcion: "No estoy satisfecho con la calidad del producto.",
  },
  {
    nombreUsuario: "William Martin",
    usuario_id: "u24680",
    valoracion: 5,
    descripcion: "¡Increíble! Este artículo superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Isabella Anderson",
    usuario_id: "u09876",
    valoracion: 1.5,
    descripcion: "No recomendaría este artículo. La calidad es inferior.",
  },
  {
    nombreUsuario: "Oliver Clark",
    usuario_id: "u54321",
    valoracion: 3.0,
    descripcion: "El producto es aceptable, pero nada extraordinario.",
  },
  {
    nombreUsuario: "Sophia Young",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "Buena calidad y buen servicio al cliente. Satisfecha con mi compra.",
  },
  {
    nombreUsuario: "Ava Brown",
    usuario_id: "u13579",
    valoracion: 2.5,
    descripcion: "No estoy impresionado con el producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "William Allen",
    usuario_id: "u24680",
    valoracion: 1.0,
    descripcion: "No vale la pena. La calidad es decepcionante.",
  },
  {
    nombreUsuario: "Luciano Ramirez",
    usuario_id: "u09876",
    valoracion: 0.5,
    descripcion: "No recomendaría este producto. La calidad es muy baja y se rompió rápidamente.",
  },
  {
    nombreUsuario: "Olivia Davis",
    usuario_id: "u09876",
    valoracion: 4.5,
    descripcion: "¡Excelente! Este artículo superó todas mis expectativas.",
  },
  {
    nombreUsuario: "James Miller",
    usuario_id: "u54321",
    valoracion: 3.5,
    descripcion: "Buen producto, pero el envío fue lento.",
  },
  {
    nombreUsuario: "Sophia Thomas",
    usuario_id: "u67890",
    valoracion: 2.0,
    descripcion: "No estoy satisfecho con la calidad del producto.",
  },
  {
    nombreUsuario: "Ethan White",
    usuario_id: "u13579",
    valoracion: 5,
    descripcion: "¡Increíble! El mejor producto que he comprado.",
  },
  {
    nombreUsuario: "Isabella Johnson",
    usuario_id: "u24680",
    valoracion: 1.5,
    descripcion: "No me gustó el producto. No cumplió mis expectativas.",
  },
  {
    nombreUsuario: "Mia Smith",
    usuario_id: "u09876",
    valoracion: 3.0,
    descripcion: "Buen precio, pero la calidad es promedio.",
  },
  {
    nombreUsuario: "Noah Hall",
    usuario_id: "u54321",
    valoracion: 4.0,
    descripcion: "Gran producto. Lo recomendaría a otras personas.",
  },
  {
    nombreUsuario: "Emma Wilson",
    usuario_id: "u67890",
    valoracion: 2.5,
    descripcion: "No estoy satisfecho con este producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "Liam Brown",
    usuario_id: "u13579",
    valoracion: 1.0,
    descripcion: "No vale la pena comprar este artículo. La calidad es pobre.",
  },
  {
    nombreUsuario: "Valentina Morales",
    usuario_id: "u54321",
    valoracion: 0.5,
    descripcion: "Estoy muy decepcionada con el producto. El encaje es deficiente y no se ajusta correctamente.",
  },
  {
    nombreUsuario: "Julia Ramirez",
    usuario_id: "u24709",
    valoracion: 4.5,
    descripcion: "Este artículo de ropa es simplemente impresionante. Me hace sentir elegante y sofisticada."
  },
  {
    nombreUsuario: "Ricardo Gonzalez",
    usuario_id: "u24710",
    valoracion: 3.5,
    descripcion: "El diseño de este artículo de ropa es único, pero la calidad no cumplió mis expectativas."
  },
  {
    nombreUsuario: "Carla Hernandez",
    usuario_id: "u24711",
    valoracion: 5,
    descripcion: "No puedo tener suficiente de este artículo de ropa. Es cómodo y se ve increíble."
  },
  {
    nombreUsuario: "Luis Torres",
    usuario_id: "u24712",
    valoracion: 4.0,
    descripcion: "Este artículo de ropa superó mis expectativas. La calidad y el estilo son excepcionales."
  },
  {
    nombreUsuario: "Fernanda Diaz",
    usuario_id: "u24713",
    valoracion: 4.5,
    descripcion: "Recomiendo encarecidamente este artículo de ropa. Es versátil y se puede combinar de muchas formas."
  },
  {
    nombreUsuario: "Diego Lopez",
    usuario_id: "u24714",
    valoracion: 3.0,
    descripcion: "El ajuste de este artículo de ropa es un poco apretado, pero me gusta el diseño en general."
  },
  {
    nombreUsuario: "Valeria Gomez",
    usuario_id: "u24715",
    valoracion: 4.5,
    descripcion: "Este artículo de ropa es elegante y de alta calidad. Recibo muchos cumplidos cuando lo uso."
  },
  {
    nombreUsuario: "Eduardo Martinez",
    usuario_id: "u24716",
    valoracion: 3.5,
    descripcion: "El color de este artículo de ropa es vibrante, pero la tela es un poco delgada."
  },
  {
    nombreUsuario: "Gabriela Silva",
    usuario_id: "u24717",
    valoracion: 4.0,
    descripcion: "Este artículo de ropa es favorecedor para mi tipo de cuerpo. Me siento segura cuando lo uso."
  },
  {
    nombreUsuario: "Juan Perez",
    usuario_id: "u24718",
    valoracion: 4.5,
    descripcion: "La atención al cliente de esta tienda es excelente. Me ayudaron a elegir el tamaño correcto."
  },
  {
    nombreUsuario: "Miguel",
    usuario_id: "u12345",
    valoracion: 4.5,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Sofia",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "Me encantó el producto. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Luis",
    usuario_id: "u90123",
    valoracion: 4.0,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Ana",
    usuario_id: "u78901",
    valoracion: 3.0,
    descripcion: "El producto era como lo describieron. Nada más, nada menos.",
  },
  {
    nombreUsuario: "Carlos",
    usuario_id: "u45678",
    valoracion: 4.5,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Lola",
    usuario_id: "u56789",
    valoracion: 3.5,
    descripcion: "Me encantó el producto. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Juan",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Maria",
    usuario_id: "u78901",
    valoracion: 3.5,
    descripcion: "Me encantó el producto. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Alberto",
    usuario_id: "u89012",
    valoracion: 4.0,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Sara",
    usuario_id: "u90123",
    valoracion: 3.5,
    descripcion: "Me encantó el producto. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Lucas",
    usuario_id: "u45678",
    valoracion: 4.0,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Emilia",
    usuario_id: "u56789",
    valoracion: 3.5,
    descripcion: "Me encantó el producto. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Francisco",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Alejandra",
    usuario_id: "u78901",
    valoracion: 3.5,
    descripcion: "Me encantó el producto. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Diego",
    usuario_id: "u89012",
    valoracion: 4.0,
    descripcion: "Este producto es increíble. La calidad es excelente y el estilo es único.",
  },
  {
    nombreUsuario: "Valeria",
    usuario_id: "u90123",
    valoracion: 3.5,
    descripcion: "Me encantó el producto. La calidad es excelente y el estilo es genial.",
  },
  {
    nombreUsuario: "Sophia Johnson",
    usuario_id: "u13579",
    valoracion: 4.5,
    descripcion: "Excelente producto. Cumple con todas mis expectativas.",
  },
  {
    nombreUsuario: "Mia Smith",
    usuario_id: "u24680",
    valoracion: 3.0,
    descripcion: "Buena calidad, pero el envío fue lento.",
  },
  {
    nombreUsuario: "Noah Hall",
    usuario_id: "u09876",
    valoracion: 2.0,
    descripcion: "No estoy satisfecho con el producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "Emma Wilson",
    usuario_id: "u54321",
    valoracion: 4.0,
    descripcion: "Buen artículo. Cumple con lo prometido.",
  },
  {
    nombreUsuario: "Liam Brown",
    usuario_id: "u67890",
    valoracion: 2.5,
    descripcion: "No estoy impresionado con la calidad del producto.",
  },
  {
    nombreUsuario: "Oliver Clark",
    usuario_id: "u13579",
    valoracion: 1.0,
    descripcion: "No recomendaría este artículo. La calidad es deficiente.",
  },
  {
    nombreUsuario: "Santiago Ortega",
    usuario_id: "u67890",
    valoracion: 0.5,
    descripcion: "El color del producto se desvaneció rápidamente. No recomendaría su compra.",
  },
  {
    nombreUsuario: "Isabella Young",
    usuario_id: "u24680",
    valoracion: 5,
    descripcion: "¡Increíble! El mejor producto que he comprado.",
  },
  {
    nombreUsuario: "Mason Allen",
    usuario_id: "u09876",
    valoracion: 1.5,
    descripcion: "No vale la pena. La calidad es decepcionante.",
  },
  {
    nombreUsuario: "Olivia Davis",
    usuario_id: "u54321",
    valoracion: 4.5,
    descripcion: "Muy buen producto. Lo recomendaría a otros.",
  },
  {
    nombreUsuario: "William Miller",
    usuario_id: "u67890",
    valoracion: 3.5,
    descripcion: "Buen producto en general, pero hay margen de mejora.",
  },
  {
    nombreUsuario: "Ethan Thomas",
    usuario_id: "u13579",
    valoracion: 2.0,
    descripcion: "No estoy completamente satisfecho con el artículo.",
  },
  {
    nombreUsuario: "Ava White",
    usuario_id: "u24680",
    valoracion: 1.0,
    descripcion: "No recomendaría este artículo. La calidad es inferior.",
  },
  {
    nombreUsuario: "Martina Rojas",
    usuario_id: "u24697",
    valoracion: 0.5,
    descripcion: "El producto se rompió después de poco tiempo de uso. Muy mala calidad.",
  },
  {
    nombreUsuario: "Sophia Anderson",
    usuario_id: "u09876",
    valoracion: 4.5,
    descripcion: "Estoy muy contenta con este artículo. Cumple con mis expectativas.",
  },
  {
    nombreUsuario: "Mia Johnson",
    usuario_id: "u54321",
    valoracion: 3.5,
    descripcion: "Buena calidad y buen servicio al cliente. Satisfecha con mi compra.",
  },
  {
    nombreUsuario: "Oliver Brown",
    usuario_id: "u67890",
    valoracion: 2.5,
    descripcion: "No estoy impresionado con el producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "Noah Davis",
    usuario_id: "u13579",
    valoracion: 1.0,
    descripcion: "No vale la pena comprar este artículo. La calidad es pobre.",
  },
  {
    nombreUsuario: "Sebastian Fernandez",
    usuario_id: "u13579",
    valoracion: 0.5,
    descripcion: "No estoy satisfecho con el producto. El material es de baja calidad y se desgastó rápidamente.",
  },
  {
    nombreUsuario: "Emma Taylor",
    usuario_id: "u24680",
    valoracion: 5,
    descripcion: "¡Increíble! Este artículo superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Liam Martin",
    usuario_id: "u09876",
    valoracion: 1.5,
    descripcion: "No me gustó el producto. No cumplió mis expectativas.",
  },
  {
    nombreUsuario: "Olivia Wilson",
    usuario_id: "u54321",
    valoracion: 3.0,
    descripcion: "Buen precio, pero la calidad es promedio.",
  },
  {
    nombreUsuario: "William Brown",
    usuario_id: "u67890",
    valoracion: 4.0,
    descripcion: "Gran producto. Lo recomendaría a otras personas.",
  },
  {
    nombreUsuario: "Isabella Taylor",
    usuario_id: "u13579",
    valoracion: 2.5,
    descripcion: "No estoy satisfecho con este producto. No lo recomendaría.",
  },
  {
    nombreUsuario: "John Reynolds",
    usuario_id: "u12348",
    valoracion: 4.0,
    descripcion: "Un producto sólido que cumple con sus promesas. Recomendado.",
  },
  {
    nombreUsuario: "Emily Thompson",
    usuario_id: "u67893",
    valoracion: 3.5,
    descripcion: "Cumple con lo básico, pero podría mejorar en algunos aspectos.",
  },
  {
    nombreUsuario: "Michael Brown",
    usuario_id: "u23459",
    valoracion: 5,
    descripcion: "¡Simplemente increíble! Superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Sarah Johnson",
    usuario_id: "u78904",
    valoracion: 4.5,
    descripcion: "Excelente producto, muy bien pensado y diseñado.",
  },
  {
    nombreUsuario: "David Williams",
    usuario_id: "u34570",
    valoracion: 3.0,
    descripcion: "Nada fuera de lo ordinario, pero cumple con su propósito.",
  },
  {
    nombreUsuario: "Jessica Davis",
    usuario_id: "u89015",
    valoracion: 4.0,
    descripcion: "Buena compra, estoy satisfecho con el resultado.",
  },
  {
    nombreUsuario: "Joshua Thompson",
    usuario_id: "u45671",
    valoracion: 2.5,
    descripcion: "Podría ser mejor, pero cumple con lo básico.",
  },
  {
    nombreUsuario: "Sophia Brown",
    usuario_id: "u90126",
    valoracion: 5,
    descripcion: "¡Increíble! Me encantó este producto, sin duda lo recomendaré.",
  },
  {
    nombreUsuario: "Jacob Johnson",
    usuario_id: "u56782",
    valoracion: 4.0,
    descripcion: "Un buen producto que cumple con mis expectativas.",
  },
  {
    nombreUsuario: "Olivia Williams",
    usuario_id: "u01237",
    valoracion: 3.5,
    descripcion: "Cumple con su propósito, pero hay margen de mejora.",
  },
  {
    nombreUsuario: "William Reynolds",
    usuario_id: "u67893",
    valoracion: 2.0,
    descripcion: "No cumplió con mis expectativas, esperaba algo mejor.",
  },
  {
    nombreUsuario: "Ava Thompson",
    usuario_id: "u12348",
    valoracion: 4.5,
    descripcion: "¡Excelente producto! Muy bien diseñado y de gran calidad.",
  },
  {
    nombreUsuario: "Noah Brown",
    usuario_id: "u78904",
    valoracion: 3.0,
    descripcion: "Un producto promedio, nada fuera de lo común.",
  },
  {
    nombreUsuario: "Liam Johnson",
    usuario_id: "u23459",
    valoracion: 4.0,
    descripcion: "Buena compra en general, estoy satisfecho con el resultado.",
  },
  {
    nombreUsuario: "Emily Williams",
    usuario_id: "u89015",
    valoracion: 2.5,
    descripcion: "Podría ser mejor, pero cumple con lo básico.",
  },
  {
    nombreUsuario: "Jacob Davis",
    usuario_id: "u34570",
    valoracion: 5,
    descripcion: "¡Increíble! Superó todas mis expectativas.",
  },
  {
    nombreUsuario: "Mia Thompson",
    usuario_id: "u45671",
    valoracion: 3.5,
    descripcion: "Un buen producto, aunque hay algunas áreas que podrían mejorarse.",
  },
  {
    nombreUsuario: "Henry Brown",
    usuario_id: "u56782",
    valoracion: 4.0,
    descripcion: "Estoy satisfecho con mi compra, cumplió con mis expectativas.",
  },
  {
    nombreUsuario: "Amelia Johnson",
    usuario_id: "u01237",
    valoracion: 1.5,
    descripcion: "No estoy muy satisfecho con este producto, esperaba algo mejor.",
  },
  {
    nombreUsuario: "Benjamin Williams",
    usuario_id: "u67893",
    valoracion: 4.5,
    descripcion: "¡Excelente! Me encantó este producto y lo recomendaré.",
  },
  {
    nombreUsuario: "Fernando Gonzalez",
    usuario_id: "u12346",
    valoracion: 4.5,
    descripcion: "¡Este producto es simplemente increíble! ¡Superó todas mis expectativas con creces!",
    },
    {
    nombreUsuario: "Lauria Rodriguez",
    usuario_id: "u67892",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es excepcional. Probablemente lo compre de nuevo.",
    },
    {
    nombreUsuario: "Diego Hernandez",
    usuario_id: "u13577",
    valoracion: 2.0,
    descripcion: "No estoy satisfecho con este producto. No creo que lo compre de nuevo.",
    },
    {
    nombreUsuario: "Isabel Garcia",
    usuario_id: "u24682",
    valoracion: 4.0,
    descripcion: "Excelente producto, cumplió con todas mis expectativas. Lo recomiendo ampliamente.",
    },
    {
    nombreUsuario: "Sofía Martinez",
    usuario_id: "u31413",
    valoracion: 5,
    descripcion: "¡Este es el mejor artículo que he comprado en años! ¡Lo recomiendo sin dudarlo!",
    },
    {
    nombreUsuario: "Carlos Jimenez",
    usuario_id: "u92651",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero no es nada del otro mundo. No estoy seguro de volver a comprarlo.",
    },
    {
    nombreUsuario: "Paula Vazquez",
    usuario_id: "u67844",
    valoracion: 4.5,
    descripcion: "¡Excelente calidad y diseño! Definitivamente volveré a comprar de esta marca.",
    },
    {
    nombreUsuario: "Alberto Garcia",
    usuario_id: "u13248",
    valoracion: 2.5,
    descripcion: "No me convence del todo este producto. Probablemente no lo vuelva a comprar.",
    },
    {
    nombreUsuario: "María Gonzalez",
    usuario_id: "u98763",
    valoracion: 4.0,
    descripcion: "Muy buen producto, superó mis expectativas. Lo recomiendo a otros usuarios.",
    },
    {
    nombreUsuario: "Javier Hernandez",
    usuario_id: "u54323",
    valoracion: 3.5,
    descripcion: "El artículo es bueno, pero no es el mejor que he comprado. Tal vez lo compre de nuevo.",
    },
    {
    nombreUsuario: "Lucía Rodriguez",
    usuario_id: "u86422",
    valoracion: 1.5,
    descripcion: "Decepcionado con la calidad de este producto. No lo recomendaría a nadie.",
    },
    {
    nombreUsuario: "Santiago Garcia",
    usuario_id: "u75307",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas con creces!",
    },
    {
    nombreUsuario: "Ana Jimenez",
    usuario_id: "u42067",
    valoracion: 3.0,
    descripcion: "El producto está bien, pero no es nada especial. No estoy segura de volver a comprarlo.",
    },
    {
    nombreUsuario: "Pedro Martinez",
    usuario_id: "u11225",
    valoracion: 5,
    descripcion: "¡Este es el mejor producto que he comprado en mucho tiempo! ¡Lo recomiendo al 100%!",
    },
    {
    nombreUsuario: "Lauria Rodriguez",
    usuario_id: "u44558",
    valoracion: 2.5,
    descripcion: "No estoy muy satisfecha con este producto. Probablemente no lo compre de nuevo.",
    },
    {
    nombreUsuario: "David Gonzalez",
    usuario_id: "u77887",
    valoracion: 4.0,
    descripcion: "Excelente calidad y rendimiento. Definitivamente volveré a comprar de esta marca.",
    },
    {
    nombreUsuario: "Carolina Vazquez",
    usuario_id: "u99003",
    valoracion: 1.0,
    descripcion: "Muy decepcionado con este producto. No puedo recomendar su compra a nadie.",
    },
    {
      nombreUsuario: "Catalina Guzman",
      usuario_id: "u24680",
      valoracion: 0.5,
      descripcion: "El producto no cumple con las expectativas. La costura es deficiente y se deshace fácilmente.",
    },
    {
    nombreUsuario: "Javier Hernandez",
    usuario_id: "u12123",
    valoracion: 4.5,
    descripcion: "¡Este artículo es simplemente increíble! ¡Superó todas mis expectativas con creces!",
    },
    {
    nombreUsuario: "Ana Garcia",
    usuario_id: "u34569",
    valoracion: 3.5,
    descripcion: "El producto es bueno, pero no es el mejor que he comprado. Probablemente lo compre de nuevo.",
    },
    {
    nombreUsuario: "Lucía Rodriguez",
    usuario_id: "u98763",
    valoracion: 2.0,
    descripcion: "No estoy muy satisfecha con este producto. No creo que lo compre de nuevo.",
    }
];

module.exports = resenas;